name: Deploy wandbox.org

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Register SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
    - name: Add SSH config
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "Host wandbox" >> $HOME/.ssh/config
        echo "    HostName $SSH_HOST" >> $HOME/.ssh/config
        echo "    User $SSH_USER" >> $HOME/.ssh/config
        echo "    ServerAliveInterval 60" >> $HOME/.ssh/config
        echo "    TCPKeepAlive yes" >> $HOME/.ssh/config
        ssh-keyscan -H $SSH_HOST >> $HOME/.ssh/known_hosts
    - name: apt install
      run: sudo apt-get install -y libcap-dev
    - name: Get cached tools
      id: cache-tools
      uses: actions/cache@v2
      with:
        path: _install
        key: install-deps
    - name: Install deps
      run: ./install_deps.sh --release
    - name: Package cattleshed
      run: |
        ./package.sh cattleshed master
    - name: Package kennel
      run: |
        ./package.sh kennel master
    - name: Deploy cattleshed to wandbox.org
      run: |
        ./deploy.sh wandbox cattleshed master
    - name: Deploy kennel to wandbox.org
      run: |
        ./deploy.sh wandbox kennel master