name: Deploy staging.wandbox.org

on:
  push:
    branches:
      - canine

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Register SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
    - name: Add SSH config
      run: |
        echo "Host kennel-root" >> $HOME/.ssh/config
        echo "    HostName 49.212.130.73" >> $HOME/.ssh/config
        echo "    User root" >> $HOME/.ssh/config
        ssh-keyscan -H 49.212.130.73 >> $HOME/.ssh/known_hosts
        echo "Host cattleshed-root" >> $HOME/.ssh/config
        echo "    HostName 153.121.40.132" >> $HOME/.ssh/config
        echo "    User root" >> $HOME/.ssh/config
        ssh-keyscan -H 153.121.40.132 >> $HOME/.ssh/known_hosts
    - name: apt install
      run: sudo apt-get install -y libcap-dev
    - name: Get cached tools
      id: cache-tools
      uses: actions/cache@v2
      with:
        path: _install
        key: install-deps
    - name: Get cached node_modules
      id: cache-node_modules
      uses: actions/cache@v2
      with:
        path: canine/node_modules
        key: node_modules
    - name: Install deps
      run: ./install_deps.sh --release
    - name: Package cattleshed
      run: |
        ./package.sh cattleshed staging
    - name: Package kennel
      run: |
        ./package.sh kennel staging
    - name: Package canine
      run: |
        ./package.sh canine staging
    - name: Deploy cattleshed to staging.wandbox.org
      run: |
        ./deploy.sh cattleshed-root cattleshed staging
    - name: Deploy kennel to staging.wandbox.org
      run: |
        ./deploy.sh kennel-root kennel staging
    - name: Deploy canine to staging.wandbox.org
      run: |
        ./deploy.sh kennel-root canine staging
